const lang = {
  en: {
    welcome: "Welcome",
    login: "Sign In",
    signup: "Sign Up",
    emailPlaceholder: "Email or phone number",
    passwordPlaceholder: "Password",
    home: "Home",
    gptSearch: "GPT Search",
    search: "Search",
    searchPlaceholder: "What would you like to watch today?",
  },
  es: {
    welcome: "Bienvenido",
    login: "Iniciar sesión",
    signup: "Regístrate",
    emailPlaceholder: "Correo electrónico o número de teléfono",
    passwordPlaceholder: "Contraseña",
    home: "Inicio",
    gptSearch: "Búsqueda GPT",
    search: "Buscar",
    searchPlaceholder: "¿Qué te gustaría ver hoy?",
  },
  fr: {
    welcome: "Bienvenue",
    login: "Se connecter",
    signup: "S'inscrire",
    emailPlaceholder: "E-mail ou numéro de téléphone",
    passwordPlaceholder: "Mot de passe",
    home: "Accueil",
    gptSearch: "Recherche GPT",
    search: "Rechercher",
    searchPlaceholder: "Que voulez-vous regarder aujourd'hui?",
  },
  hin: {
    welcome: "स्वागत है",
    login: "साइन इन",
    signup: "साइन अप",
    emailPlaceholder: "ईमेल या फोन नंबर",
    passwordPlaceholder: "पासवर्ड",
    home: "होम",
    gptSearch: "जीपीटी खोज",
    search: "खोजें",
    searchPlaceholder: "आज आप क्या देखना चाहेंगे?",
  },
  tel: {
    welcome: "స్వాగతం",
    login: "సైన్ ఇన్",
    signup: "సైన్ అప్",
    emailPlaceholder: "ఇమెయిల్ లేదా ఫోన్ నంబర్",
    passwordPlaceholder: "పాస్వర్డ్",
    home: "హోమ్",
    gptSearch: "జీపీటీ శోధన",
    search: "శోధించండి",
    searchPlaceholder: "ఈ రోజు మీరు ఏమి చూడాలనుకుంటున్నారు?",
  },
};

export default lang;
